<section class="section dashboard-page"><div class="container">
    <div class="page-heading"><div><span class="eyebrow">Test Mode operations</span><h1>Refund management</h1><p class="muted">Monitor and safely retry idempotent Razorpay Test Mode refunds.</p></div><form method="post" action="<?= e(url('admin/refunds/process')) ?>"><?= csrf_field() ?><button class="button" type="submit">Process next 10</button></form></div>
    <?php if ($success): ?><div class="alert alert-success"><?= e($success) ?></div><?php endif; ?>
    <?php if ($error): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?>
    <form class="catalog-filters management-booking-filters" method="get" action="<?= e(url('admin/refunds')) ?>">
        <div class="catalog-search-field"><label for="refund-search">Search</label><input id="refund-search" name="q" value="<?= e($filters['search']) ?>" placeholder="Booking, event, or customer email"></div>
        <div><label for="refund-status">Status</label><select id="refund-status" name="status"><?php foreach (['any','pending','processing','processed','failed'] as $status): ?><option value="<?= e($status) ?>" <?= $filters['status'] === $status ? 'selected' : '' ?>><?= e(ucfirst($status)) ?></option><?php endforeach; ?></select></div>
        <div><label for="refund-source">Source</label><select id="refund-source" name="source"><?php foreach (['any','customer','event'] as $source): ?><option value="<?= e($source) ?>" <?= $filters['source'] === $source ? 'selected' : '' ?>><?= e(ucfirst($source)) ?></option><?php endforeach; ?></select></div>
        <div class="catalog-filter-actions"><button class="button button-compact" type="submit">Filter</button><a class="button button-secondary button-compact" href="<?= e(url('admin/refunds')) ?>">Reset</a></div>
    </form>
    <p class="catalog-result-summary"><span><?= e($total) ?> refund(s)</span><span>Page <?= e($page) ?> of <?= e($pageCount) ?></span></p>
    <?php if ($refunds === []): ?><div class="empty-state"><h2>No refunds found</h2></div><?php else: ?><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Booking / customer</th><th>Event</th><th>Tickets</th><th>Amount</th><th>Source</th><th>Status</th></tr></thead><tbody>
        <?php foreach ($refunds as $refund): ?><tr><td><a href="<?= e(url('admin/refunds/' . $refund['id'])) ?>"><strong><?= e($refund['refund_reference']) ?></strong></a><small><?= e(local_datetime($refund['requested_at'])) ?></small></td><td><?= e($refund['booking_reference']) ?><small><?= e($refund['customer_name']) ?> &middot; <?= e($refund['customer_email']) ?></small></td><td><?= e($refund['event_title']) ?></td><td><?= e($refund['ticket_count']) ?></td><td><?= e(money($refund['amount'])) ?><small><?= e($refund['refund_percentage']) ?>%</small></td><td><?= e($refund['source']) ?></td><td><span class="status-badge status-<?= e($refund['status']) ?>"><?= e($refund['status']) ?></span></td></tr><?php endforeach; ?>
    </tbody></table></div><?php endif; ?>
    <?php if ($pageCount > 1): ?><nav class="pagination" aria-label="Refund pages"><?php if ($page > 1): ?><a href="<?= e(url('admin/refunds?' . http_build_query(['q' => $filters['search'], 'status' => $filters['status'], 'source' => $filters['source'], 'page' => $page - 1]))) ?>">&larr; Previous</a><?php else: ?><span></span><?php endif; ?><span>Page <?= e($page) ?> of <?= e($pageCount) ?></span><?php if ($page < $pageCount): ?><a href="<?= e(url('admin/refunds?' . http_build_query(['q' => $filters['search'], 'status' => $filters['status'], 'source' => $filters['source'], 'page' => $page + 1]))) ?>">Next &rarr;</a><?php else: ?><span></span><?php endif; ?></nav><?php endif; ?>
</div></section>
