<section class="section dashboard-page"><div class="container form-page">
    <div class="page-heading"><div><span class="eyebrow">Refund record</span><h1><?= e($refund['refund_reference']) ?></h1><p class="muted">Razorpay Test Mode</p></div><a class="button button-secondary" href="<?= e(url('admin/refunds')) ?>">All refunds</a></div>
    <?php if ($success): ?><div class="alert alert-success"><?= e($success) ?></div><?php endif; ?>
    <?php if ($error): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?>
    <div class="panel"><dl class="details-list"><div><dt>Status</dt><dd><span class="status-badge status-<?= e($refund['status']) ?>"><?= e($refund['status']) ?></span></dd></div><div><dt>Booking</dt><dd><a href="<?= e(url('admin/bookings/' . $refund['booking_id'])) ?>"><?= e($refund['booking_reference']) ?></a></dd></div><div><dt>Customer</dt><dd><?= e($refund['customer_name']) ?> &middot; <?= e($refund['customer_email']) ?></dd></div><div><dt>Event</dt><dd><?= e($refund['event_title']) ?></dd></div><div><dt>Refund</dt><dd><?= e(money($refund['amount'])) ?> at <?= e($refund['refund_percentage']) ?>%</dd></div><div><dt>Source</dt><dd><?= e($refund['source']) ?> cancellation</dd></div><div><dt>Attempts</dt><dd><?= e($refund['attempt_count']) ?></dd></div><div><dt>Requested</dt><dd><?= e(local_datetime($refund['requested_at'])) ?></dd></div></dl>
        <?php if ($refund['failure_description']): ?><div class="alert alert-error">The last Test Mode refund attempt failed. Review server logs for operational details, then retry safely.</div><?php endif; ?>
        <?php if (in_array($refund['status'], ['pending','processing','failed'], true)): ?><form method="post" action="<?= e(url('admin/refunds/' . $refund['id'] . '/retry')) ?>" data-confirm="Retry this refund using its existing idempotency key?"><?= csrf_field() ?><button class="button" type="submit">Retry refund</button></form><?php endif; ?>
    </div>
    <section class="panel"><div class="panel-heading"><div><span class="eyebrow">Cancelled inventory</span><h2>Tickets</h2></div></div><div class="table-wrap"><table><thead><tr><th>Ticket code</th><th>Type</th><th>Seat</th><th>Original</th><th>Refund</th></tr></thead><tbody><?php foreach ($tickets as $ticket): ?><tr><td><code><?= e($ticket['ticket_code']) ?></code></td><td><?= e($ticket['ticket_type_name']) ?></td><td>S-<?= e(str_pad((string) $ticket['seat_number'], 3, '0', STR_PAD_LEFT)) ?></td><td><?= e(money($ticket['gross_amount'])) ?></td><td><?= e(money($ticket['refund_amount'])) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</div></section>
