<section class="section dashboard-page"><div class="container">
    <div class="page-heading"><div><span class="eyebrow">Platform review</span><h1>Event cancellation requests</h1><p class="muted">Approval closes the event, invalidates valid tickets, restores inventory, and queues full Test Mode refunds.</p></div></div>
    <?php if ($success): ?><div class="alert alert-success"><?= e($success) ?></div><?php endif; ?>
    <?php if ($error): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?>
    <form class="catalog-filters customer-management-filters" method="get" action="<?= e(url('admin/cancellations')) ?>"><div><label for="cancellation-search">Search</label><input id="cancellation-search" name="q" value="<?= e($search) ?>" placeholder="Event, organizer, or email"></div><div><label for="cancellation-status">Status</label><select id="cancellation-status" name="status"><?php foreach (['pending','approved','rejected','withdrawn','any'] as $status): ?><option value="<?= e($status) ?>" <?= $selectedStatus === $status ? 'selected' : '' ?>><?= e(ucfirst($status)) ?></option><?php endforeach; ?></select></div><div class="catalog-filter-actions"><button class="button button-compact" type="submit">Filter</button><a class="button button-secondary button-compact" href="<?= e(url('admin/cancellations')) ?>">Reset</a></div></form>
    <p class="catalog-result-summary"><span><?= e($total) ?> request(s)</span><span>Page <?= e($page) ?> of <?= e($pageCount) ?></span></p>
    <?php if ($requests === []): ?><div class="empty-state"><h2>No matching requests</h2><p>There are no event cancellation requests in this state.</p></div><?php else: ?><div class="table-wrap"><table><thead><tr><th>Event</th><th>Organizer</th><th>Impact</th><th>Reason</th><th>Status</th><th>Decision</th></tr></thead><tbody>
        <?php foreach ($requests as $request): ?><tr><td><strong><?= e($request['title']) ?></strong><small><?= e(local_datetime($request['start_datetime'])) ?></small></td><td><?= e($request['organizer_name']) ?><small><?= e($request['organizer_email']) ?></small></td><td><?= e($request['affected_bookings']) ?> bookings<small><?= e(money($request['booked_value'])) ?> booked value</small></td><td><?= e($request['reason']) ?></td><td><span class="status-badge status-<?= e($request['status']) ?>"><?= e($request['status']) ?></span></td><td><?php if ($request['status'] === 'pending'): ?><div class="cancellation-review-actions"><form method="post" action="<?= e(url('admin/cancellations/' . $request['id'] . '/approve')) ?>" data-confirm="Cancel this event and queue full refunds for all remaining valid paid tickets?"><?= csrf_field() ?><input name="review_note" maxlength="1000" placeholder="Review note (optional)"><button class="button button-danger button-compact" type="submit">Approve cancellation</button></form><form method="post" action="<?= e(url('admin/cancellations/' . $request['id'] . '/reject')) ?>"><?= csrf_field() ?><input name="review_note" maxlength="1000" placeholder="Review note (optional)"><button class="button button-secondary button-compact" type="submit">Reject</button></form></div><?php else: ?><?= e($request['review_note'] ?: '—') ?><?php endif; ?></td></tr><?php endforeach; ?>
    </tbody></table></div><?php endif; ?>
    <?php if ($pageCount > 1): ?><nav class="pagination" aria-label="Cancellation pages"><?php if ($page > 1): ?><a href="<?= e(url('admin/cancellations?' . http_build_query(['q' => $search, 'status' => $selectedStatus, 'page' => $page - 1]))) ?>">&larr; Previous</a><?php else: ?><span></span><?php endif; ?><span>Page <?= e($page) ?> of <?= e($pageCount) ?></span><?php if ($page < $pageCount): ?><a href="<?= e(url('admin/cancellations?' . http_build_query(['q' => $search, 'status' => $selectedStatus, 'page' => $page + 1]))) ?>">Next &rarr;</a><?php else: ?><span></span><?php endif; ?></nav><?php endif; ?>
</div></section>
